"""Build every LaTeX table and figure used by the PA1 report from saved result files.

Run from the repository root:
    python report/scripts/make_report_assets.py

Inputs are the machine-readable results under task1/ ... task4/results/.
Outputs go to report/tables/*.tex and report/figures/*.
Nothing here is typed by hand, so each reported number traces to a result file.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT_T = ROOT / "report" / "tables"
OUT_F = ROOT / "report" / "figures"

T1 = ROOT / "task1" / "results"
T2 = ROOT / "task2" / "results"
T3 = ROOT / "task3" / "results"
T4 = ROOT / "task4" / "results"

PACS_CLASSES = ["dog", "elephant", "giraffe", "guitar", "horse", "house", "person"]
SOURCES = [("photo", "P"), ("art_painting", "A"), ("cartoon", "C")]

T1_MODELS = [
    ("resnet50", "ResNet-50 (head)"),
    ("vit_b_16", "ViT-B/16 (head)"),
    ("clip_vit_b_32", "CLIP ViT-B/32 (head)"),
    ("clip_zeroshot", "CLIP ViT-B/32 (zero-shot)"),
]
T1_BACKBONES = [m for m in T1_MODELS if m[0] != "clip_zeroshot"]

plt.rcParams.update(
    {
        "font.family": "serif",
        "font.size": 8,
        "axes.titlesize": 8,
        "axes.labelsize": 8,
        "legend.fontsize": 7,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
    }
)
TEXTWIDTH_IN = 5.5


def load(path: Path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def pct(x: float, nd: int = 1) -> str:
    return f"{100 * x:.{nd}f}"


def signed_pct(x: float, nd: int = 1) -> str:
    v = 100 * x
    if abs(v) < 0.5 * 10 ** (-nd):
        v = 0.0
    return f"${v:+.{nd}f}$"


def write_table(name: str, sources: list[Path], body: str) -> None:
    header = (
        f"% Auto-generated by report/scripts/make_report_assets.py. Do not edit by hand.\n"
        f"% Sources: {', '.join(rel(s) for s in sources)}\n"
    )
    (OUT_T / f"{name}.tex").write_text(header + body, encoding="utf-8")
    print(f"table  {name}.tex")


def tabular(colspec: str, head: list[str], rows: list[list[str]], extra_head: str = "") -> str:
    lines = [f"\\begin{{tabular}}{{{colspec}}}", "\\toprule"]
    if extra_head:
        lines.append(extra_head)
    lines.append(" & ".join(head) + " \\\\")
    lines.append("\\midrule")
    for r in rows:
        if r == ["MIDRULE"]:
            lines.append("\\midrule")
        else:
            lines.append(" & ".join(r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------- Task 1


def task1_tables() -> None:
    src = T1 / "tables" / "task1_summary.json"
    d = load(src)

    clean = d["clean"]["metrics"]
    rows = [
        [label, pct(clean[k]["top1_accuracy"]), pct(clean[k]["macro_f1"]), f"{clean[k]['mean_max_confidence']:.3f}"]
        for k, label in T1_MODELS
    ]
    write_table(
        "t1_clean",
        [src],
        tabular("lccc", ["Model", "Top-1 (\\%)", "Macro-F1 (\\%)", "Mean max conf."], rows),
    )

    color, shuffle = d["color"], d["patch_shuffle"]["metrics"]
    rows = []
    for k, label in T1_MODELS:
        row = [label, pct(clean[k]["top1_accuracy"])]
        for cond in (color["grayscale"][k], color["hue_rotate"][k], shuffle[k]):
            row += [
                f"{pct(cond['top1_accuracy'])} ({signed_pct(cond['accuracy_change'])})",
                pct(cond["prediction_consistency"]),
            ]
        rows.append(row)
    extra = (
        " & Clean & \\multicolumn{2}{c}{Grayscale} & \\multicolumn{2}{c}{Hue rotation "
        f"{color['assumptions']['hue_degrees']:.0f}$^\\circ$}} & \\multicolumn{{2}}{{c}}{{Patch shuffle $4\\times4$}} \\\\\n"
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}"
    )
    write_table(
        "t1_interventions",
        [src],
        tabular(
            "lccccccc",
            ["Model", "Acc", "Acc ($\\Delta$)", "Cons.", "Acc ($\\Delta$)", "Cons.", "Acc ($\\Delta$)", "Cons."],
            rows,
            extra_head=extra,
        ),
    )

    cc = d["cue_conflict"]
    rows = []
    for k, label in T1_MODELS:
        m = cc["models"][k]
        rows.append(
            [
                label,
                str(m["n_shape"]),
                str(m["n_texture"]),
                str(m["n_other"]),
                f"{m['shape_bias_pct']:.1f}",
                f"{m['coverage_pct']:.1f}",
            ]
        )
    write_table(
        "t1_cue_conflict",
        [src],
        f"% accepted conflicts = {cc['n_accepted']}, rejected = {cc['n_rejected']}\n"
        + tabular(
            "lccccc",
            ["Model", "$N_{\\text{shape}}$", "$N_{\\text{texture}}$", "$N_{\\text{other}}$", "Shape bias (\\%)", "Coverage (\\%)"],
            rows,
        ),
    )

    fs = d["feature_similarity"]["results"]
    rows = [
        [
            label,
            f"{fs[k]['grayscale']:.3f}",
            f"{fs[k]['cue_conflict_vs_content']:.3f}",
            f"{fs[k]['translation_16px_right']:.3f}",
            f"{fs[k]['patch_shuffle']:.3f}",
        ]
        for k, label in T1_BACKBONES
    ]
    notes = "".join(f"% note: {n}\n" for n in d["feature_similarity"]["notes"])
    write_table(
        "t1_stability",
        [src],
        notes
        + tabular(
            "lcccc",
            ["Backbone", "Grayscale", "Cue conflict", "Translation (16 px)", "Patch shuffle"],
            rows,
        ),
    )

    tr = d["translation"]
    shifts = [e["displacement"] for e in tr["resnet50"]]
    rows = []
    for k, label in T1_MODELS:
        by = {e["displacement"]: e for e in tr[k]}
        rows.append([label] + [f"{pct(by[s]['top1_accuracy'])} / {pct(by[s]['prediction_consistency'])}" for s in shifts])
    write_table(
        "t1_translation",
        [src],
        tabular("l" + "c" * len(shifts), ["Model"] + [f"$\\delta={s}$" for s in shifts], rows),
    )


def task1_figures() -> None:
    d = load(T1 / "tables" / "task1_summary.json")["translation"]
    fig, axes = plt.subplots(1, 2, figsize=(TEXTWIDTH_IN, 1.9))
    for k, label in T1_MODELS:
        xs = [e["displacement"] for e in d[k]]
        axes[0].plot(xs, [100 * e["top1_accuracy"] for e in d[k]], marker="o", ms=3, label=label)
        axes[1].plot(xs, [100 * e["prediction_consistency"] for e in d[k]], marker="o", ms=3, label=label)
    for ax, ylab in zip(axes, ["Top-1 accuracy (%)", "Consistency (%)"]):
        ax.set_xlabel("Displacement $\\delta$ (px)")
        ax.set_ylabel(ylab)
        ax.set_xticks(xs)
        ax.grid(alpha=0.3, lw=0.5)
    axes[1].legend(frameon=False, loc="lower left")
    fig.savefig(OUT_F / "t1_translation.pdf")
    plt.close(fig)
    print("figure t1_translation.pdf")

    copies = {
        T1 / "figures" / "resnet50_grayscale_tsne.png": "t1_tsne_resnet50_grayscale.png",
        T1 / "figures" / "vit_b_16_grayscale_tsne.png": "t1_tsne_vit_grayscale.png",
        T1 / "figures" / "clip_vit_b_32_grayscale_tsne.png": "t1_tsne_clip_grayscale.png",
        T1 / "figures" / "resnet50_patch_shuffle_tsne.png": "t1_tsne_resnet50_shuffle.png",
        T1 / "figures" / "vit_b_16_patch_shuffle_tsne.png": "t1_tsne_vit_shuffle.png",
        T1 / "figures" / "clip_vit_b_32_patch_shuffle_tsne.png": "t1_tsne_clip_shuffle.png",
        T1 / "figures" / "intervention_gallery" / "cue_conflicts_examples.png": "t1_cue_conflict_examples.png",
        T1 / "figures" / "intervention_gallery" / "interventions_color_spatial.png": "t1_interventions_gallery.png",
    }
    copy_figures(copies)


# ---------------------------------------------------------------- Task 2


def per_domain_cell(entry: dict, dom: str) -> str:
    v = entry["source_val_per_domain"][dom]
    return f"{pct(v['accuracy'])} / {pct(v['macro_f1'])}"


T2_MAIN = [
    ("source_only_best", "Source-only (ERM)"),
    ("dan_lambda1.0_best", "DAN ($\\lambda_{\\text{MMD}}=1$)"),
    ("dann_best", "DANN"),
    ("cdan_best", "CDAN"),
]


def task2_tables() -> None:
    src = T2 / "tables" / "task2_main_comparison.json"
    by_run = {e["run"]: e for e in load(src)["table"]}
    rows = []
    for run, label in T2_MAIN:
        e = by_run[run]
        rows.append(
            [label]
            + [per_domain_cell(e, dom) for dom, _ in SOURCES]
            + [
                pct(e["mean_source_accuracy"]),
                pct(e["mean_source_macro_f1"]),
                pct(e["target_accuracy"]),
                pct(e["target_macro_f1"]),
                signed_pct(e["target_accuracy_change_vs_source_only"]),
                pct(e["domain_separability"]),
            ]
        )
    extra = (
        " & \\multicolumn{3}{c}{Source val. (Acc / F1)} & \\multicolumn{2}{c}{Mean source} & "
        "\\multicolumn{3}{c}{Sketch (target)} & \\\\\n"
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-9}"
    )
    write_table(
        "t2_main",
        [src],
        tabular(
            "lccccccccc",
            ["Method", "P", "A", "C", "Acc", "F1", "Acc", "F1", "$\\Delta$Acc", "Dom. sep."],
            rows,
            extra_head=extra,
        ),
    )

    src_l = T2 / "tables" / "task2_lambda_study.json"
    src_c = T2 / "figures" / "feature_tsne" / "centroid_distances.json"
    cent = load(src_c)
    rows = []
    for e in sorted(load(src_l)["table"], key=lambda r: float(r["run"].split("lambda")[1].split("_")[0])):
        lam = float(e["run"].split("lambda")[1].split("_")[0])
        tag = e["run"].replace("_best", "")
        rows.append(
            [
                f"{lam:g}",
                pct(e["mean_source_accuracy"]),
                pct(e["mean_source_macro_f1"]),
                pct(e["domain_separability"]),
                f"{cent[tag]['centroid_l2']:.1f}" if tag in cent else "--",
                pct(e["target_accuracy"]),
                pct(e["target_macro_f1"]),
                signed_pct(e["target_accuracy_change_vs_source_only"]),
            ]
        )
    write_table(
        "t2_lambda",
        [src_l, src_c],
        "% centroid L2 = distance between mean source-val and mean Sketch feature (450 each), from the t-SNE diagnostic\n"
        + tabular(
            "cccccccc",
            [
                "$\\lambda_{\\text{MMD}}$",
                "Src Acc",
                "Src F1",
                "Dom. sep.",
                "Centroid $\\ell_2$",
                "Sketch Acc",
                "Sketch F1",
                "$\\Delta$Acc",
            ],
            rows,
        ),
    )


def curve_panels(runs: list[tuple[Path, str]], out_name: str, align_label: str, worst: bool = False) -> None:
    n = 4 if worst else 3
    fig, axes = plt.subplots(1, n, figsize=(TEXTWIDTH_IN, 1.7))
    for path, label in runs:
        h = load(path)
        ep = [r["epoch"] for r in h]
        f1 = [100 * r["source_val"]["mean_macro_f1"] for r in h]
        best = max(range(len(f1)), key=lambda i: f1[i])
        (line,) = axes[0].plot(ep, [r["train"]["cls_loss"] for r in h], lw=1, label=label)
        c = line.get_color()
        align = [r["train"]["align_loss"] for r in h]
        if any(a != 0 for a in align):
            axes[1].plot(ep, align, lw=1, color=c)
        axes[2].plot(ep, f1, lw=1, color=c)
        axes[2].plot(ep[best], f1[best], marker="*", ms=6, color=c)
        if worst:
            wf = [100 * min(v["macro_f1"] for v in r["source_val"]["per_domain"].values()) for r in h]
            axes[3].plot(ep, wf, lw=1, color=c)
            axes[3].plot(ep[best], wf[best], marker="*", ms=6, color=c)
    titles = ["Classification loss", align_label, "Mean source-val macro-F1 (%)"]
    if worst:
        titles.append("Worst source-val macro-F1 (%)")
    for ax, t in zip(axes, titles):
        ax.set_title(t)
        ax.set_xlabel("Epoch")
        ax.grid(alpha=0.3, lw=0.5)
    axes[1].set_yscale("log")
    fig.legend(*axes[0].get_legend_handles_labels(), loc="upper center", ncol=len(runs), frameon=False, bbox_to_anchor=(0.5, 1.12))
    fig.tight_layout(w_pad=0.6)
    fig.savefig(OUT_F / out_name)
    plt.close(fig)
    print(f"figure {out_name}")


def task2_figures() -> None:
    c = T2 / "curves"
    curve_panels(
        [
            (c / "source_only_history.json", "Source-only"),
            (c / "dan_lambda1.0_history.json", "DAN ($\\lambda$=1)"),
            (c / "dann_history.json", "DANN"),
            (c / "cdan_history.json", "CDAN"),
        ],
        "t2_curves.pdf",
        "Alignment loss (MMD$^2$ or domain CE)",
    )
    curve_panels(
        [
            (c / "dan_lambda0.1_history.json", "DAN $\\lambda$=0.1"),
            (c / "dan_lambda1.0_history.json", "DAN $\\lambda$=1"),
            (c / "dan_lambda10.0_history.json", "DAN $\\lambda$=10"),
        ],
        "t2_lambda_curves.pdf",
        "MMD$^2$ penalty",
    )
    fts = T2 / "figures" / "feature_tsne"
    runs = {"source_only": "source_only", "dan_lambda1.0": "dan_lam1", "dann": "dann", "cdan": "cdan", "dan_lambda10.0": "dan_lam10"}
    copies = {fts / f"{r}_tsne.png": f"t2_tsne_{short}.png" for r, short in runs.items()}
    copies.update({fts / f"{r}_domain_only.png": f"t2_tsne_domain_{short}.png" for r, short in runs.items()})
    copies[T2 / "figures" / "pacs_gallery" / "classes_across_domains.png"] = "t2_pacs_classes_across_domains.png"
    copy_figures(copies)


# ---------------------------------------------------------------- Task 3

T3_MAIN = [
    ("source_only", "ERM (Task 2 source-only)"),
    ("dan_dg_lambda1.0", "DAN-DG ($\\lambda_{\\text{DG}}=1$)"),
    ("sam_rho0.05", "SAM ($\\rho=0.05$)"),
]


def task3_tables() -> None:
    src = T3 / "tables" / "task3_main_comparison.json"
    by_run = {e["run"]: e for e in load(src)["table"]}
    rows = []
    for run, label in T3_MAIN:
        e = by_run[run]
        rows.append(
            [label]
            + [per_domain_cell(e, dom) for dom, _ in SOURCES]
            + [
                f"{pct(e['mean_source_accuracy'])} / {pct(e['mean_source_macro_f1'])}",
                f"{pct(e['worst_source_accuracy'])} / {pct(e['worst_source_macro_f1'])}",
                f"{pct(e['sketch_accuracy'])} / {pct(e['sketch_macro_f1'])}",
                signed_pct(e["sketch_accuracy_change_vs_erm"]),
                pct(e["source_domain_separability"]),
                f"{e['delta_sharp']:.3f}",
            ]
        )
    extra = (
        " & \\multicolumn{5}{c}{Source validation (Acc / F1)} & & & & \\\\\n"
        "\\cmidrule(lr){2-6}"
    )
    write_table(
        "t3_main",
        [src],
        tabular(
            "lccccccccc",
            ["Method", "P", "A", "C", "Mean", "Worst", "Sketch (Acc / F1)", "$\\Delta$Acc", "Src sep.", "$\\Delta_{\\text{sharp}}$"],
            rows,
            extra_head=extra,
        ),
    )

    src_l = T3 / "tables" / "task3_lambda_study.json"
    rows = [
        [
            f"{e['lambda_dg']:g}",
            pct(e["mean_source_macro_f1"]),
            pct(e["worst_source_macro_f1"]),
            pct(e["source_domain_separability"]),
            f"{e['delta_sharp']:.3f}",
            pct(e["sketch_accuracy"]),
            pct(e["sketch_macro_f1"]),
        ]
        for e in load(src_l)["table"]
    ]
    write_table(
        "t3_lambda",
        [src_l],
        tabular(
            "ccccccc",
            ["$\\lambda_{\\text{DG}}$", "Mean src F1", "Worst src F1", "Src sep.", "$\\Delta_{\\text{sharp}}$", "Sketch Acc", "Sketch F1"],
            rows,
        ),
    )


def task3_figures() -> None:
    c3 = T3 / "curves"
    curve_panels(
        [
            (T2 / "curves" / "source_only_history.json", "ERM"),
            (c3 / "dan_dg_lambda1.0_history.json", "DAN-DG ($\\lambda$=1)"),
            (c3 / "sam_rho0.05_history.json", "SAM ($\\rho$=0.05)"),
        ],
        "t3_curves.pdf",
        "Pairwise source MMD$^2$",
        worst=True,
    )
    curve_panels(
        [
            (c3 / "dan_dg_lambda0.1_history.json", "$\\lambda_{DG}$=0.1"),
            (c3 / "dan_dg_lambda1.0_history.json", "$\\lambda_{DG}$=1"),
            (c3 / "dan_dg_lambda10.0_history.json", "$\\lambda_{DG}$=10"),
        ],
        "t3_lambda_curves.pdf",
        "Pairwise source MMD$^2$",
        worst=True,
    )


# ------------------------------------------------------- Task 2 + 3 per-class

PERCLASS_RUNS = [
    ("ERM", T2 / "tables" / "eval_source_only_best.json", "target_per_class"),
    ("DAN", T2 / "tables" / "eval_dan_lambda1.0_best.json", "target_per_class"),
    ("DANN", T2 / "tables" / "eval_dann_best.json", "target_per_class"),
    ("CDAN", T2 / "tables" / "eval_cdan_best.json", "target_per_class"),
    ("DAN-DG", T3 / "tables" / "eval_dan_dg_lambda1.0.json", "sketch_per_class"),
    ("SAM", T3 / "tables" / "eval_sam_rho0.05.json", "sketch_per_class"),
]


def perclass_table_and_figure() -> None:
    accs, counts = {}, {}
    confs = {}
    for name, path, key in PERCLASS_RUNS:
        d = load(path)
        accs[name] = {c: d[key][c]["accuracy"] for c in PACS_CLASSES}
        counts = {c: d[key][c]["n"] for c in PACS_CLASSES}
        confs[name] = d.get("target_confusions_top") or d.get("sketch_confusions_top")

    base = accs["ERM"]
    rows = []
    for c in PACS_CLASSES:
        row = [f"{c} ({counts[c]})", pct(base[c])]
        for name, _, _ in PERCLASS_RUNS[1:]:
            row.append(f"{pct(accs[name][c])} ({signed_pct(accs[name][c] - base[c])})")
        rows.append(row)
    extra = (
        " & & \\multicolumn{3}{c}{Task 2 (sees unlabeled Sketch)} & \\multicolumn{2}{c}{Task 3 (Sketch unseen)} \\\\\n"
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-7}"
    )
    write_table(
        "t23_perclass",
        [p for _, p, _ in PERCLASS_RUNS],
        "% cells: Sketch per-class accuracy (change vs ERM), in percent; (n) = Sketch images per class\n"
        + tabular("lcccccc", ["Class ($n$)"] + [n for n, _, _ in PERCLASS_RUNS], rows, extra_head=extra),
    )

    rows = []
    for name, _, _ in PERCLASS_RUNS:
        top = confs[name][:3]
        rows.append([name] + [f"{t['true']}$\\to${t['pred']} ({t['count']})" for t in top])
    write_table(
        "t23_confusions",
        [p for _, p, _ in PERCLASS_RUNS],
        tabular("llll", ["Model", "1st", "2nd", "3rd"], rows),
    )

    fig, axes = plt.subplots(1, 2, figsize=(TEXTWIDTH_IN, 1.9), sharey=True)
    groups = [(axes[0], ["DAN", "DANN", "CDAN"], "Task 2 (UDA) vs. ERM"), (axes[1], ["DAN-DG", "SAM"], "Task 3 (DG) vs. ERM")]
    xs = range(len(PACS_CLASSES))
    for ax, names, title in groups:
        w = 0.8 / len(names)
        for i, name in enumerate(names):
            ax.bar(
                [x - 0.4 + w * (i + 0.5) for x in xs],
                [100 * (accs[name][c] - base[c]) for c in PACS_CLASSES],
                width=w,
                label=name,
            )
        ax.axhline(0, color="k", lw=0.6)
        ax.set_xticks(list(xs))
        ax.set_xticklabels(PACS_CLASSES, rotation=35, ha="right")
        ax.set_title(title)
        ax.grid(axis="y", alpha=0.3, lw=0.5)
        ax.legend(frameon=False, fontsize=6.5)
    axes[0].set_ylabel("$\\Delta$ Sketch accuracy (pp)")
    fig.tight_layout(w_pad=0.8)
    fig.savefig(OUT_F / "t23_perclass_delta.pdf")
    plt.close(fig)
    print("figure t23_perclass_delta.pdf")


def cross_task_separability_figure() -> None:
    """Separability vs. Sketch accuracy for every Task 2 and Task 3 run (two separate probes)."""
    t2 = load(T2 / "tables" / "task2_main_comparison.json")["table"]
    t3 = load(T3 / "tables" / "task3_main_comparison.json")["table"]
    t3l = load(T3 / "tables" / "task3_lambda_study.json")["table"]
    fig, axes = plt.subplots(1, 2, figsize=(TEXTWIDTH_IN, 2.0))
    t2_names = {
        "source_only_best": "ERM",
        "dan_lambda0.1_best": "DAN $\\lambda$=0.1",
        "dan_lambda1.0_best": "DAN $\\lambda$=1",
        "dan_lambda10.0_best": "DAN $\\lambda$=10",
        "dann_best": "DANN",
        "cdan_best": "CDAN",
    }
    for e in t2:
        lbl = t2_names[e["run"]]
        axes[0].scatter(100 * e["domain_separability"], 100 * e["target_accuracy"], s=14)
        axes[0].annotate(lbl, (100 * e["domain_separability"], 100 * e["target_accuracy"]), fontsize=6, xytext=(3, 2), textcoords="offset points")
    axes[0].set_xlabel("Source vs. Sketch separability (%)  [chance 50]")
    axes[0].set_ylabel("Sketch accuracy (%)")
    axes[0].set_title("Task 2: target-aware alignment")
    pts = [(e["source_domain_separability"], e["sketch_accuracy"], {"source_only": "ERM", "dan_dg_lambda1.0": "DAN-DG $\\lambda$=1", "sam_rho0.05": "SAM"}[e["run"]]) for e in t3]
    pts += [(e["source_domain_separability"], e["sketch_accuracy"], f"DAN-DG $\\lambda$={e['lambda_dg']:g}") for e in t3l if e["lambda_dg"] != 1.0]
    for s, a, lbl in pts:
        axes[1].scatter(100 * s, 100 * a, s=14)
        axes[1].annotate(lbl, (100 * s, 100 * a), fontsize=6, xytext=(3, 2), textcoords="offset points")
    axes[1].set_xlabel("P/A/C source-domain separability (%)  [chance 33.3]")
    axes[1].set_title("Task 3: source-only alignment")
    for ax in axes:
        ax.grid(alpha=0.3, lw=0.5)
    fig.tight_layout(w_pad=1.0)
    fig.savefig(OUT_F / "t23_separability_vs_sketch.pdf")
    plt.close(fig)
    print("figure t23_separability_vs_sketch.pdf")


# ---------------------------------------------------------------- Task 4

SCORE_NAMES = {"msp": "MSP", "mls": "MLS", "energy": "Energy", "mahalanobis": "Mahalanobis", "proser_placeholder": "PROSER placeholder"}
MODEL_NAMES = {"vanilla": "Vanilla", "gcsc": "GCSC", "proser": "PROSER"}


def osr_cells(r: dict) -> list[str]:
    return [
        pct(r["auroc_near"]),
        pct(r["auroc_far"]),
        pct(r["auroc_all"]),
        pct(r["known_test_accept_rate"]),
        pct(r["near_reject_rate"]),
        pct(r["far_reject_rate"]),
        pct(r["near_fpr_at_95tpr"]),
        pct(r["far_fpr_at_95tpr"]),
    ]


OSR_EXTRA = (
    "\\multicolumn{3}{c}{AUROC (\\%)} & \\multicolumn{3}{c}{At $\\tau$ = val. 95th pct. (\\%)} & \\multicolumn{2}{c}{FPR@95TPR (\\%)} \\\\\n"
)


def task4_tables() -> None:
    src = T4 / "tables" / "task4_score_comparison.json"
    rows = [[SCORE_NAMES[r["score"]]] + osr_cells(r) for r in load(src)["rows"]]
    head = ["Score $u(x)$", "Near", "Far", "All", "Known acc.", "Near rej.", "Far rej.", "Near", "Far"]
    write_table(
        "t4_scores",
        [src],
        tabular(
            "lcccccccc",
            head,
            rows,
            extra_head=" & " + OSR_EXTRA + "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-9}",
        ),
    )

    src = T4 / "tables" / "task4_model_comparison.json"
    rows = [[f"{MODEL_NAMES[r['model']]} + {SCORE_NAMES[r['score']]}", pct(r["csa"])] + osr_cells(r) for r in load(src)["rows"]]
    head = ["Model + score", "CSA"] + head[1:]
    write_table(
        "t4_models",
        [src],
        tabular(
            "lccccccccc",
            head,
            rows,
            extra_head=" & & " + OSR_EXTRA + "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\\cmidrule(lr){9-10}",
        ),
    )

    src = T4 / "tables" / "task4_failure_analysis.json"
    rows = [
        [
            f["group"].capitalize(),
            f["unknown_class"].replace("_", "\\_"),
            f["predicted_cifar10"],
            f"{f['unknownness_u']:.2f}",
            f"{f['threshold_tau']:.2f}",
        ]
        for f in load(src)["failures"]
    ]
    write_table(
        "t4_failures",
        [src],
        tabular("lllcc", ["Group", "CIFAR-100 class", "Predicted", "$u_{\\text{MLS}}(x)$", "$\\tau$"], rows),
    )


def task4_figures() -> None:
    fig, ax = plt.subplots(figsize=(TEXTWIDTH_IN / 2, 1.8))
    for name in ["gcsc", "proser"]:
        h = load(T4 / "curves" / f"{name}_history.json")["history"]
        ax.plot([r["epoch"] for r in h], [100 * r["val_acc"] for r in h], lw=1, label=MODEL_NAMES[name])
    van = load(T4 / "tables" / "vanilla_train_summary.json")
    ax.axhline(100 * van["best_val_acc"], ls="--", lw=0.8, color="gray", label="Vanilla best (history lost)")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("CIFAR-10 val. accuracy (%)")
    ax.set_ylim(80, 100)
    ax.grid(alpha=0.3, lw=0.5)
    ax.legend(frameon=False)
    fig.savefig(OUT_F / "t4_val_curves.pdf")
    plt.close(fig)
    print("figure t4_val_curves.pdf")
    copy_figures({T4 / "figures" / "score_distributions.png": "t4_score_distributions.png"})


# ---------------------------------------------------------------- utils


def copy_figures(mapping: dict[Path, str]) -> None:
    for src, dst in mapping.items():
        if src.exists():
            shutil.copy2(src, OUT_F / dst)
            print(f"copy   {dst}")
        else:
            print(f"MISSING {rel(src)}")


def main() -> None:
    OUT_T.mkdir(parents=True, exist_ok=True)
    OUT_F.mkdir(parents=True, exist_ok=True)
    task1_tables()
    task1_figures()
    task2_tables()
    task2_figures()
    task3_tables()
    task3_figures()
    perclass_table_and_figure()
    cross_task_separability_figure()
    task4_tables()
    task4_figures()


if __name__ == "__main__":
    main()
